class Dialogos(object):
    def __init__(self):
        self.Ready = 1
        self.dialogos = []
    def UnoPiloto(self):
       self.dialogos.clear()
       self.dialogos.append( "Por favor podrías dibujarme un borrego..")
       self.dialogos.append( "Qué?")
       self.dialogos.append( "Dibújame un borrego.")
       self.dialogos.append( "Pero...Qué haces tú ahí ? ")
       self.dialogos.append( "Por favor dibújame un borrego ")
       self.dialogos.append( "Yo no sé dibujar. ")
       self.dialogos.append( "Eso no importa; dibújame un borrego ")
        #Dibuja la serpiente jeje
       self.dialogos.append( "No, no! yo no quiero un elefante dentro de una boa, Un elefante es muy estorboso y una boa es muy peligrosa. Dibújame un borrego por favor. ")
       self.dialogos.append( "Toma! ")
        #Dibujo borrego 1
       self.dialogos.append( "No, este se ve ya muy enfermo. Hazme otro. ")
       self.dialogos.append( "Y éste? ")
        #Dibujo borrego 2
       self.dialogos.append( "Fíjate bien, este no es un borrego; más bien es un carnero; tiene cuernos. ")
       self.dialogos.append( "Toma éste otro ")
        #Dibujo borrego 3
       self.dialogos.append( "Este está demasiado viejo; yo quiero un borrego que viva mucho tiempo.")
       self.dialogos.append( "Aquí está otro; mira, aqui adentro está el borrego que quieres ")
        #Dibujo de la caja 
       self.dialogos.append( "Es exactamente como lo quería. Tú crees que necesite mucha hierba? ")
       self.dialogos.append( "Por qué? ")
       self.dialogos.append( "Porque donde yo vivo todo es muy pequeño.")
       self.dialogos.append( "Alcanzará seguramente. Te he dibujado un borrego bien pequeño. ")
       self.dialogos.append( "No tan pequeño. Mira, ya se durmió ")
        #NARRACION
    def DosAvion(self):
       self.dialogos.clear()
       self.dialogos.append( "Y qué es esa cosa? ")
       self.dialogos.append( " No es una cosa. Vuela. Es un avión...Es mí avión.")
       self.dialogos.append( "Cómo? Has caido del cielo? ")
       self.dialogos.append( "Sí. ")
       self.dialogos.append( "Ah! Que gracioso! ")
       self.dialogos.append( "Entonces...Tú tambien vienes del cielo! De qué planeta eres? ")
       self.dialogos.append( "Vienes de otro planeta? ")
       self.dialogos.append( "La verdad es que, en esto, no puedes haber venido de muy lejos...")
       self.dialogos.append( "De donde vienes, hombrecito? Donde queda 'Tu casa'? A dónde quieres llevarte mi cordero? ")
       self.dialogos.append( " Me gusta la caja que me hs regalado porque de noche servirá de casa.")
       self.dialogos.append( " Seguramente. y si eres amable te daré también una cuerda para atarlo durante el día. Y una estaca.")
       self.dialogos.append( "Atarlo? !Qué idea tan rara! ")
       self.dialogos.append( "Pero si no lo atas se irá a cualquier parte y se perderá... ")
       self.dialogos.append( "Pero, Adónde quieres que vaya? ")
       self.dialogos.append( "A cualquier parte. Derecho, siempre adelante... ")
       self.dialogos.append( "No importa! Mi casa es muy pequeña... Delante, siempre adelante de uno... No se puede ir muy lejos. ")
        #NARRACIÓN
    def TresPuesta(self):
       self.dialogos.clear()
       self.dialogos.append( "Me encantan las puestas de sol. Vamos a ver una puesta del sol. ")
       self.dialogos.append( "Pero tenemos que esperar. ")
       self.dialogos.append( "Esperar qué? ")
       self.dialogos.append( "Esperar a que el sol se ponga. ")
       self.dialogos.append( "Me creo siempre en mi casa! ")
       self.dialogos.append( "... ")
      # self.dialogos.append( "... ")
       self.dialogos.append( "Un día, vi ponerse el sol cuarenta y tres veces. ")
       self.dialogos.append( "... ")
       self.dialogos.append( "Sabes?... Cuando uno está verdaderamente triste son agradables las puestas de sol. ")
       self.dialogos.append( "Estabas, pues, verdaderamente triste el día de las cuarenta y tres veces? ")
    def CuatroEspinas(self):
       self.dialogos.clear()
       self.dialogos.append( "Si un borrego come arbustos, Come tambien flores?")
       self.dialogos.append( "Un cordero come todo lo que encuentra. ")
       self.dialogos.append( "Hasta las flores con espinas? ")
       self.dialogos.append( "Sí, hasta las flores con espinas. ")
       self.dialogos.append( "Entonces Para qué sirven las espinas? ")
       self.dialogos.append( "... ")
       self.dialogos.append( "Para qué sirven las espinas? ")
       self.dialogos.append( "... ")
       self.dialogos.append( "Para qué sirven las espinas? ")
       self.dialogos.append( "Las espinas no sirven para nada. Son pura maldad de las flores! ")
       self.dialogos.append( "Oh!.. ")
       self.dialogos.append( "... ")
       self.dialogos.append( "... ")
       self.dialogos.append( "No te creo...Las flores son débiles. Son ingenuas. Se defienden como pueden. Se creen terribles con sus espinas. ")
       self.dialogos.append( "... ")
       self.dialogos.append( "Y tú, tú crees que las flores...? ")
       self.dialogos.append( "No, no no! Yo no creo nada! Te contesté cualquier cosa pero estoy ocupado, Yo me ocupo de cosas serias! ")
       self.dialogos.append( "De cosas serias!...Confundes todo!...Conozco un planeta donde vive un señor carmesí. Jamás ha querido a nadie.No ha hecho más que sumas y restas. Y todo el día repute como tú: 'Soy un hombre serio! Soy un hombre serio!' Se infla de orgullo. Pero no es un hombre, es, Es un hongo! ")
       self.dialogos.append( "Un qué? ")
       self.dialogos.append( "Un hongo! ")
       self.dialogos.append( "Hace millones de años que las flores fabrican espinas. Hace millones de años que los cordetros comen igualmente las flores. Y no es serio intentar comprender por qué las flores se esfuerzan tanto en fabricar espinas que no sirven nunca para nada? No es importante la guerra de los corderos y las flores? No es ,as serio y mas importante que las sumas de un señor gordo y rojo? ")
       self.dialogos.append( "... ")
       self.dialogos.append( "Y no es importante que yo conozca una flor única en el mundo, que no existe en ninguna parte salvo mi planeta, y que un corderito puede aniquilar una mañana, así, de un solo golpe, sin darsecuenta de lo que hace?...Esto,No es importante? ")
       self.dialogos.append( "... ")
       self.dialogos.append( "Si alguien ama una flor de las que no existe más, que un ejemplar entre millones y millones de estrellas, es bastante para que sea feliz cuando mira las estrellas. se dice 'Mi flor está allí, en alguna parte...'Y si el cordero come la flor, para él es como si, bruscamente, todas las estrellas se apagaran. Y esto, No es importante? ")
        #NARRACIÓN -el principito llora :c-
    def CincoFlor(self):
       self.dialogos.clear()
       self.dialogos.append( "Ah!, acabo de despertarme...Perdóname...Todavía estoy toda despeinada... ")
       self.dialogos.append( "Qué hermosa eres! ")
       self.dialogos.append( "Verdad?, Y he nacido al mismo tiempo que el sol. Creo que es hora del desayuno, Tendrías la bondad de acordarte de mi?")
       self.dialogos.append( "Claro ")
       self.dialogos.append( "Sabes? yo no le tengo miedo a los tigres, yo tengo mis espinas. ")
       self.dialogos.append( "En mi planeta no hay tigres, además, los tigres no comen hierba. ")
       self.dialogos.append( "Yo no soy hierba ! ")
       self.dialogos.append( "Ah ! discúlpame. ")
       self.dialogos.append( "No me dan miedo los tigres, en cambio les tengo horror a las corrientes de aire. No tendrás un biombo? ")
       self.dialogos.append( "Eh, si, claro... ")
       self.dialogos.append( "Por la noche me meterás bajo un globo. Aquí hace mucho frío. Hay pocas comodidades. Allá de donde vengo...mmm...bueno...Y el biomo? ")
       self.dialogos.append( "Lo iba a buscar! Pero como me estabas hablando... ")
        #Esto se lo dice al piloto
       self.dialogos.append( "No debí haberla escuchado, Nunca hay que escuchar a las flores, hay que mirarlas y aspirar su aroma. La mía perfumaba mi planeta, pero yo no podía gozar con ello. La historia de las garras, que tanto me había fastidiado, debe haberme enternecido... ")
       self.dialogos.append( "Entiendo. ")
       self.dialogos.append( "No supe comprender nada entonces. Debí haberla juzgado por sus actos y no por sus palabras. Me perfumaba e iluminada. No debí haber huido jamás! Debí haber adivinado su ternura, detrás de sus pobres astucias. Las flores son tan contradictorias! Pero yo era demasaido joven para saber amarla.")
    #NARRACIÓN
    def SeisByeFlor(self):
       self.dialogos.clear()
       self.dialogos.append( "Adiós. ")
       self.dialogos.append( "Adiós ")
       self.dialogos.append( "*He...He sido tonta...Te pido perdón. Procura ser feliz. ")
       self.dialogos.append( "... ")
       self.dialogos.append( "Pero...Sí, te quiero. No has sabido nada, por mi culpa. No tiene importancia. Pero has sido tan tonto como yo. Procura ser Feliz...Deja el globo en paz. No lo quiero más. ")
       self.dialogos.append( "Pero el viento... ")
       self.dialogos.append( "No estoy tan resfriada como para...El aire fresco de la noche me hara bien, soy una flor. ")
       self.dialogos.append( "Pero los animales... ")
       self.dialogos.append( "Es preciso que soporte dos o tres orugas si quiero conocer las mariposas. Parece que es tan hermoso! si no, Quién habrá de visitarme? Tú estarás lejos. En cuantto los animales grandes, no les temo. Tengo mis garras. ")
       self.dialogos.append( "... ")
       self.dialogos.append( "No te detengas, has decidido partir. Vete. ")
       self.dialogos.append( " ")
        #NARRACIÓN -creo-
    def SieteRey(self):
       self.dialogos.clear()
       self.dialogos.append( "Ah! He ahí un súbdito, Ven, acércate. ")
       self.dialogos.append( "Cómo puede reconocerme si nunca me ha visto antes? ")
       self.dialogos.append( "Acércate para que te vea mejor. ")
       self.dialogos.append( "Uaaaah")
       self.dialogos.append( "Es contrario a la etiqueta bostezar en presencia de un rey. Yo te lo prohíbo. ")
       self.dialogos.append( "No puedo evitarlo; vengo de un largo viaje y no he dormido. ")
       self.dialogos.append( "Entonces te ordeno bostezar. No he visto a nadie bostezar en varios años. Los bostezos son para mí algo curioso. Vamos! bosteza otra vez, Es una orden! ")
       self.dialogos.append( "Eso me intimida...  Así ya no puedo bostezar... ")
       self.dialogos.append( "Mmm. esta bien, esta bien. entonces te... te ordeno bostezar o no bostezar... Hum... ")
       self.dialogos.append( "Puedo sentarme? ")
       self.dialogos.append( "Te ordeno sentarte ")
       self.dialogos.append( " Majestad, le pido disculpas por interrogarlo... ")
       self.dialogos.append( "Yo te ordeno que me interrogues. ")
       self.dialogos.append( "Majestad, Sobre qué reina usted? ")
       self.dialogos.append( "Sobre todo. ")
       self.dialogos.append( "Sobre todo? Y las estrellas le obedecen?")
       self.dialogos.append( "Por supuesto. Las estrellas me obedecen inmediatamente; yo no tolero la indisciplina. ")
       self.dialogos.append( "Majestad, me gustaría una puesta de sol... Podría usted darme ese placer... Ordene usted al sol que se ponga. ")
       self.dialogos.append( "Si ordeno a un general que vuele de flor en flor como una mariposa, o que escriba una tragedia, o que se transforme en ave y el general no equecuta esa orden, Quén, o yo, estaría en falta? ")
       self.dialogos.append( "Usted ")
       self.dialogos.append( "Exacto. Hay que exigir a cada uno lo que cada uno puede hacer. La autoridad reposa en primer término, sobre la razón. Si ordenas a tu pueblo que vaya a arrojarse al mar, hará una revolución. Tengo derecho a exigir obediencia porque mis ordenes son razonables. ")
       self.dialogos.append( "Y mi puesta de sol? ")
       self.dialogos.append( "La tendrás. Lo exigiré. Pero esperaré, con mi ciencia de gobernante, a que las condiciones sean favorables. ")
       self.dialogos.append( "Cuándo serán faborables las condiciones? ")
       self.dialogos.append( "Hem...Pues...Mmm...Será a las...A las siete cuarenta! Verás como soy obedecido! ")
       self.dialogos.append( "Bueno, no tengo nada que hacer aqui. Voy a partir. ")
       self.dialogos.append( " No te vayas y... Y te haré ministro! ")
       self.dialogos.append( "Ministro de qué? ")
       self.dialogos.append( "De...De justicia! ")
       self.dialogos.append( "Pero aquí no hay nadie a quién juzgar. ")
       self.dialogos.append( "Te juzgarás a ti mismo. Es lo más dificil. Es mucho más dificil juzgarse a sí mismo que juzgar a los demás. Si logras juzgarte bien a ti mismo eres un verdadero sabio. ")
       self.dialogos.append( "Puedo juzgarme en cualquier parte. No tengo necesidad de vivir aquí. ")
       self.dialogos.append( "Mm, mm, yo estoy seguro que en mi planeta existe en algún lugar una vieja rata; tu puedes condenarla a muerte algunas veces y luego perdonarla para economizarla, ya que no hay más que una. ")
       self.dialogos.append( "Pero a mi no me parece bien condenar a muerte a nadie. Mejor me voy. ")
       self.dialogos.append( " No, !No he ordenado que te vayas ! ")
       self.dialogos.append( " Si vuestra majestad desea ser obedecido, puede ordenarme partir. Las condiciones son favorables. ")
       self.dialogos.append( "Puedo nombrarte embajador! ")
       self.dialogos.append( "Los adultos son verdaderamente extraños. ")
        #NARRADOR 
    def OchoVanidoso(self):
       self.dialogos.clear()
       self.dialogos.append( "Ah! Ah! He aquí la visita de un admirador! ")
       self.dialogos.append( " Buenos días, tienes un sombrero extraño. ")
       self.dialogos.append( "Es para saludar cuando me aclaman. Desgraciadamente no pasa nadie por aquí.  ")
       self.dialogos.append( "Ah si? ")
       self.dialogos.append( "Golpea tus manos una contra la otra. ")
       self.dialogos.append( "*Clap Clap* ")
        #Se supone que el principito aplaude y el vanidoso saluda con su sombrero. Varias veces
       self.dialogos.append( "Esto es mas divertido que la visita al rey.")
        #Sigue aplaudiendo jeje "
       self.dialogos.append( "Y, Qué hay que hacer para que el sombrero caiga?  ")
       self.dialogos.append( "Me admiras mucho verdaderamente? ")
       self.dialogos.append( "Qué significa admirar? ")
       self.dialogos.append( "Admirar significa reconocer que soy el hombre más hermoso, mejor vestido, más rico y más inteligente del planeta. ")
       self.dialogos.append( "Pero si eres la única persona en el planeta! ")
       self.dialogos.append( "Hazme el placer! Admírame lo mismo! ")
       self.dialogos.append( "Te admiro, pero, Por qué puede interesarte que te admire?... Las personas grandes son decididamente muy extrañas")
    def NueveBebedor(self):
       self.dialogos.clear()
       self.dialogos.append( "Qué haces ahí? ")
       self.dialogos.append( "Bebo ")
       self.dialogos.append( "Por qué bebes? ")
       self.dialogos.append( "Para olvidar ")
       self.dialogos.append( "Para olvidar qué ")
       self.dialogos.append( "Para olvidar que tengo vergüenza ")
       self.dialogos.append( "Vergüenza de qué? ")
       self.dialogos.append( "Vergüenza de beber! ")
       self.dialogos.append( "Las personas grandes son decididamente muy pero muy extrañas " )
    def OnceNegocios(self):
       self.dialogos.clear()
       self.dialogos.append( "Buenos días. Su cigarrillo está apagado.  ")
       self.dialogos.append( "Tres y dos son cinco. Cinco y siete, doce. Doce y tres, quince. Buenos días. Quince y siete, veintidós. Veintidós y seis, veintiocho. No tengo tiempo para volver a encenderlo. Veintiséis y cinco, treinta y uno. Uf! Da un total, pues, de quinientos un millones seiscientos veintidós mil setecientos treinta y uno. ")
       self.dialogos.append( "Quinientos millones de qué? ")
       self.dialogos.append( "Eh! Estás siempre ahí? Quinientos un millones de... Ya no sé... Tengo tanto trabajo! Yo soy serio, no me divierto con tonterías. Dos y cinco, siete... ")
       self.dialogos.append( "Quinientos millones de qué? ")
       self.dialogos.append( "En los cincuenta y cuatro años que habito este planeta, sólo he sido molestado tres veces. La primera fue hace veintidós años por un abejorro que cayó Dios sabe de dónde. La segunda fue hace once años por un ataque de reumatismo. Me hace falta ejercicio. No tengo tiempo para moverme. Yo soy serio. La tercera vez... Hela aquí! Decía, pues, quinientos un millones... ")
       self.dialogos.append( "Millones de qué? ")
       self.dialogos.append( "Millones de esas cositas que se ven a veces en el cielo. ")
       self.dialogos.append( "Moscas? ")
       self.dialogos.append( "Pero no, cositas que brillan. ")
       self.dialogos.append( "Abejas? ")
       self.dialogos.append( "Pero no! Cositas doradas que hacen desvariar a los holgazanes. Pero yo soy serio! No tengo tiempo para desvariar ")
       self.dialogos.append( "Ah! Estrellas? ")
       self.dialogos.append( "Eso es. Estrellas. ")
       self.dialogos.append( "Y qué haces tú con quinientos millones de estrellas? ")
       self.dialogos.append( "Quinientos un millones seiscientos veintidós mil se tecientos treinta y uno. Yo soy serio, soy preciso. ")
       self.dialogos.append( "Y qué haces con esas estrellas? ")
       self.dialogos.append( "Qué hago? ")
       self.dialogos.append( "Sí. ")
       self.dialogos.append( "Nada. Las poseo. ")
       self.dialogos.append( "Posees las estrellas? ")
       self.dialogos.append( "Sí ")
       self.dialogos.append( "Pero he visto un rey que... ")
       self.dialogos.append( "Los reyes no poseen; “reinan”. Es muy diferente. ")
       self.dialogos.append( "Y para qué te sirve poseer las estrellas? ")
       self.dialogos.append( "Me sirve para ser rico. ")
       self.dialogos.append( "Y para qué te sirve ser rico? ")
       self.dialogos.append( "Para comprar otras estrellas, si alguien las encuentra. ")
       self.dialogos.append( "Cómo se puede poseer estrellas? ")
       self.dialogos.append( "De quién son? ")
       self.dialogos.append( "No sé. De nadie. ")
       self.dialogos.append( "Entonces, son mías, pues soy el primero en haberlo pensado. ")
       self.dialogos.append( "Es suficiente? ")
       self.dialogos.append( "Seguramente. Cuando encuentras un diamante que no es de nadie, es tuyo. Cuando encuentras una isla que no es de nadie, es tuya. Cuando eres el primero en tener una idea, la haces patentar; es tuya. Yo poseo las estrellas porque jamás, nadie antes que yo, soñó con poseerlas. ")
       self.dialogos.append( "Es verdad. Y qué haces tú con las estrellas? ")
       self.dialogos.append( "Las administro. Las cuento y las recuento. Es difícil. Pero soy un hombre serio!")
       self.dialogos.append( "Yo, si poseo un pañuelo, puedo ponerlo alrededor de mi cuello y llevármelo. Yo, si poseo una flor, puedo cortarla y llevármela. Pero tú no puedes cortar las estrellas! ")
       self.dialogos.append( "No, pero puedo depositarlas en el banco. ")
       self.dialogos.append( "Qué quiere decir eso? ")
       self.dialogos.append( "Quiere decir que escribo en un papelito la cantidad de mis estrellas. Y después cierro el papelito, bajo llave, en un cajón. ")
       self.dialogos.append( "Es todo? ")
       self.dialogos.append( "Es suficiente. ")
       self.dialogos.append( "Yo...poseo una flor que riego todos los días. Poseo tres volcanes que deshollino todas las semanas . Es útil para mis volcanes y es útil para mi flor que yo los posea. Pero tú no eres útil a las estrellas...")
    def DoceFarolero(self):
       self.dialogos.clear()
        #NARRACIÓN DE LO QUE HACE EL FAROLERO
       self.dialogos.append( "Tal vez este hombre es absurdo. Sin embargo, es menos absurdo que el rey, que el vanidoso, que el hombre de negocios y que el bebedor. Por lo menos su trabajo tiene sentido. Cuando enciende el farol es como si hiciera nacer una estrella más, o una flor. Cuando apaga el farol, hace dormir a la flor o a la estrella. Es una ocupación muy linda. Es verdaderamente útil porque es linda.")
       self.dialogos.append( "Buenos días. Por qué acabas de apagar el farol? ")
       self.dialogos.append( "Es la consigna.  Buenos días. ")
       self.dialogos.append( "Qué es la consigna? ")
       self.dialogos.append( "Apagar el farol. Buenas noches.  ")
       self.dialogos.append( "Pero, por qué acabas de encenderlo? ")
       self.dialogos.append( "Es la consigna ")
       self.dialogos.append( "No comprendo ")
       self.dialogos.append( "No hay nada que comprender.  La consigna es la consigna. Buenos días...Tengo un oficio terrible. Antes era razonable. Apagaba por la mañana y encendía por la noche. Tenía el resto del día para descansar, y el resto de la noche para dormir... ")
       self.dialogos.append( "Y después de esa época, la consigna cambió? ")
       self.dialogos.append( "La consigna no ha cambiado. Ahí está el drama! De año en año el planeta gira más rápido y la consigna no ha cambiado ")
       self.dialogos.append( "Entonces? ")
       self.dialogos.append( "Entonces, ahora que da una vuelta por minuto, no tengo un segundo de descanso. Enciendo y apago una vez por minuto. ")
       self.dialogos.append( "Qué raro! En tu planeta los días duran un minuto! ")
       self.dialogos.append( "No es raro en absoluto. Hace ya un mes que estamos hablando juntos. ")
       self.dialogos.append( "Un mes? ")
       self.dialogos.append( "Sí. Treinta minutos. Treinta días! Buenas noches. ")
       self.dialogos.append( "Sabes?..., conozco un medio para que descanses cuando quieras... ")
       self.dialogos.append( "Siempre quiero ")
       self.dialogos.append( "Tu planeta es tan pequeño que puedes recorrerlo en tres zancadas. No tienes más que caminar bastante lentamente para quedar siempre al sol. Cuando quieras descansar, caminarás... y el día durará tanto tiempo como quieras. ")
       self.dialogos.append( "Con eso no adelanto gran cosa. Lo que me gusta en la vida es dormir. ")
       self.dialogos.append( "Es no tener suerte ")
       self.dialogos.append( "Es no tener suerte...Buenos días. ")
       self.dialogos.append( "Éste es el único de quien pude haberme hecho amigo. Pero su planeta es verdaderamente demasiado pequeño. No hay lugar para dos... ")
    def DoceFarolero(self):
        #NARRACIÓN DE LO QUE HACE EL FAROLERO
        self.dialogos.clear()
        self.dialogos.append(  "Tal vez este hombre es absurdo. Sin embargo, es menos absurdo que el rey, que el vanidoso, que el hombre de negocios y que el bebedor. Por lo menos su trabajo tiene sentido. Cuando enciende el farol es como si hiciera nacer una estrella más, o una flor. Cuando apaga el farol, hace dormir a la flor o a la estrella. Es una ocupación muy linda. Es verdaderamente útil porque es linda.")
        self.dialogos.append(  "Buenos días. Por qué acabas de apagar el farol? ")
        self.dialogos.append(  "Es la consigna.  Buenos días. ")
        self.dialogos.append(  "Qué es la consigna? ")
        self.dialogos.append(  "Apagar el farol. Buenas noches.  ")
        self.dialogos.append(  "Pero, por qué acabas de encenderlo? ")
        self.dialogos.append(  "Es la consigna ")
        self.dialogos.append(  "No comprendo ")
        self.dialogos.append(  "No hay nada que comprender.  La consigna es la consigna. Buenos días...Tengo un oficio terrible. Antes era razonable. Apagaba por la mañana y encendía por la noche. Tenía el resto del día para descansar, y el resto de la noche para dormir... ")
        self.dialogos.append(  "Y después de esa época, la consigna cambió? ")
        self.dialogos.append(  "La consigna no ha cambiado. Ahí está el drama! De año en año el planeta gira más rápido y la consigna no ha cambiado ")
        self.dialogos.append(  "Entonces? ")
        self.dialogos.append(  "Entonces, ahora que da una vuelta por minuto, no tengo un segundo de descanso. Enciendo y apago una vez por minuto. ")
        self.dialogos.append(  "Qué raro! En tu planeta los días duran un minuto! ")
        self.dialogos.append(  "No es raro en absoluto. Hace ya un mes que estamos hablando juntos. ")
        self.dialogos.append(  "Un mes? ")
        self.dialogos.append(  "Sí. Treinta minutos. Treinta días! Buenas noches. ")
        self.dialogos.append(  "Sabes?..., conozco un medio para que descanses cuando quieras... ")
        self.dialogos.append(  "Siempre quiero ")
        self.dialogos.append(  "Tu planeta es tan pequeño que puedes recorrerlo en tres zancadas. No tienes más que caminar bastante lentamente para quedar siempre al sol. Cuando quieras descansar, caminarás... y el día durará tanto tiempo como quieras. ")
        self.dialogos.append(  "Con eso no adelanto gran cosa. Lo que me gusta en la vida es dormir. ")
        self.dialogos.append(  "Es no tener suerte ")
        self.dialogos.append(  "Es no tener suerte...Buenos días. ")
        self.dialogos.append(  "Éste es el único de quien pude haberme hecho amigo. Pero su planeta es verdaderamente demasiado pequeño. No hay lugar para dos... ")
        #NARRACIÓN
    def TreceGeografo(self):
        self.dialogos.clear()
        self.dialogos.append(  "Toma! He aquí un explorador, De dónde vienes? ")
        self.dialogos.append(  "Qué es este grueso libro? Qué haces aquí?")
        self.dialogos.append(  "Soy geógrafo ")
        self.dialogos.append(  "Qué es un geógrafo? ")
        self.dialogos.append(  "Es un sabio que conoce dónde se encuentran los mares, los ríos, las ciudades, las montañas y los desiertos. ")
        self.dialogos.append(  "Es bien interesante. Por fin un verdadero oficio!. Es muy bello vuestro planeta. Tiene océanos? ")
        self.dialogos.append(  "No puedo saberlo ")
        self.dialogos.append(  "Ah!...Y montañas? ")
        self.dialogos.append(  "No puedo saberlo ")
        self.dialogos.append(  "Y ciudades y ríos desiertos? ")
        self.dialogos.append(  "Tampoco puedo saberlo ")
        self.dialogos.append(  "Pero eres geógrafo! ")
        self.dialogos.append(  "Es cierto. pero no soy explorador. Carezco absolutamente de exploradores. No es el geógrafo quien debe hacer el cómputo de las ciudades, de los ríos, de las montañas, de los mares, de los océanos y de los desiertos. El geógrafo es demasiado importante para ambular. No debe dejar su despacho. Pero recibe allí a los exploradores. Les interroga y toma nota de sus observaciones. Y si las observaciones de alguno le parecen interesantes, el geógrafo hace levantar una encuesta acerca de la moralidad del explorador.  ")
        self.dialogos.append(  "Por qué? ")
        self.dialogos.append(  "Porque un explorador que mintiera ocasionaría desbarajustes en los libros de geografía Y también un explorador que bebiera demasiado ")
        self.dialogos.append(  "Por qué? ")
        self.dialogos.append(  "Porque los ebrios ven doble. Entonces el geógrafo señalaría dos montañas donde no hay más que una sola. ")
        self.dialogos.append(  "Conozco a alguien que sería un mal explorador")
        self.dialogos.append(  "Es posible. Por tanto, cuando la moralidad del explorador parece aceptable, se hacen averiguaciones acerca de su descubrimiento. ")
        self.dialogos.append(  "Se va a ver? ")
        self.dialogos.append(  "No. Es demasiado complicado. Pero se exige al explorador que presente pruebas. Si se trata, por ejemplo, del descubrimiento de una gran montaña, se le exige que traiga grandes piedras. ")
        self.dialogos.append(  "Oh... ")
        self.dialogos.append(  "Pero tú, tú vienes de lejos! Eres explorador! Vas a describirme tu planeta!...Decías? ")
        self.dialogos.append(  "Oh! Mi planeta. No es muy interesante, es muy pequeño. Tengo tres volcanes. Dos volcanes en actividad y un volcán extinto. Pero no se sabe nunca ")
        self.dialogos.append(  "No se sabe nunca ")
        self.dialogos.append(  "Tengo también una flor ")
        self.dialogos.append(  "No anotamos las flores ")
        self.dialogos.append(  "Por qué? Es lo más lindo! ")
        self.dialogos.append(  "Porque las flores son efímeras. ")
        self.dialogos.append(  "Qué significa “efímera”? ")
        self.dialogos.append(  "Las geografías son los libros más valiosos de todos los libros. Nunca pasan de moda. Es muy raro que una montaña cambie de lugar. Es muy raro que un océano pierda su agua. Escribimos cosas eternas. ")
        self.dialogos.append(  "Pero los volcanes extinguidos pueden despertarse.  Qué significa “efímera”? ")
        self.dialogos.append(  "Que los volcanes estén extinguidos o se hayan despertado es lo mismo para nosotros. Lo que cuenta para nosotros es la montaña. La montaña no cambia ")
        self.dialogos.append(  "Pero, qué significa “efímera”?  ")
        self.dialogos.append(  "Significa “que está amenazado por una próxima desaparición” ")
        self.dialogos.append(  "Mi flor está amenazada por una próxima desaparición? ")
        self.dialogos.append(  "Seguramente. ")
        self.dialogos.append(  "Mi flor es efímera, se dijo el principito, y sólo tiene cuatro espinas para defenderse contra el mundo!...Este, bueno, Qué me aconsejáis que vaya a visitar? ")
        self.dialogos.append(  "El planeta Tierra tiene buena reputación... ")
        #NARRACIÓN no se que tan larga porque ya llegó a la tierra jiji
    def CatorceSerpiente(self):
        self.dialogos.clear()
        self.dialogos.append(  "Buenas noches ")
        self.dialogos.append(  "Buenas noches ")
        self.dialogos.append(  "En qué planeta he caído? ")
        self.dialogos.append(  "En la Tierra, en África ")
        self.dialogos.append(  "Ah!... No hay, pues, nadie en la Tierra? ")
        self.dialogos.append(  "Aquí es el desierto. En los desiertos no hay nadie. La Tierra es grande ")
        self.dialogos.append(  "Me pregunto si las estrellas están encendidas a fin de que cada uno pueda encontrar la suya algún día. Mira mi planeta. Está justo sobre nosotros... Pero, qué lejos está! ")
        self.dialogos.append(  "Qué hermoso es! Qué vienes a hacer aquí? ")
        self.dialogos.append(  "Estoy disgustado con una flor ")
        self.dialogos.append(  "Ah! ")
        self.dialogos.append(  "Dónde están los hombres? Se está un poco solo en el desierto... ")
        self.dialogos.append(  "Con los hombres también se está solo ")
        self.dialogos.append(  "Eres un animal raro ")
        self.dialogos.append(  "Delgado como un dedo... ")
        self.dialogos.append(  "Pero soy más poderoso que el dedo de un rey ")
        self.dialogos.append(  "No eres muy poderoso... ni siquiera tienes patas... ni siquiera puedes viajar... ")
        self.dialogos.append(  "Puedo llevarte más lejos que un navío. A quien toco, lo vuelvo a la tierra de donde salió...Pero tú eres puro y vienes de una estrella...")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Me das lástima, tú, tan débil, sobre esta Tierra de granito. Puedo ayudarte si algún día extrañas demasiado a tu planeta. Puedo... ")
        self.dialogos.append(  "Oh! Te he comprendido muy bien, pero, por qué hablas siempre con enigmas? ")
        self.dialogos.append(  "Yo los resuelvo todos ")
    def QuinceFlores(self):
        self.dialogos.clear()
        self.dialogos.append(  "Buenos días ")
        self.dialogos.append(  "Buenos días ")
        self.dialogos.append(  "Quiénes sois? ")
        self.dialogos.append(  "Somos rosas ")
        self.dialogos.append(  "Ah! ...Mi flor me había contado que era la única de su especie en el universo...Me creía rico con una flor única y no poseo más que una rosa ordinaria. La rosa y mis tres volcanes que me llegan a la rodilla, uno de los cuales quizá está apagado para siempre. Realmente no soy un gran príncipe..." )
    def DieciseisZorro(self):
        self.dialogos.clear()
        self.dialogos.append(  "Buenos días ")
        self.dialogos.append(  "Buenos días ")
        self.dialogos.append(  "Estoy acá  ")
        self.dialogos.append(  "Quién eres? Eres muy lindo... ")
        self.dialogos.append(  "Soy un zorro ")
        self.dialogos.append(  "Ven a jugar conmigo Estoy tan triste!...")
        self.dialogos.append(  "No puedo jugar contigo. No estoy domesticado ")
        self.dialogos.append(  "Ah! Perdón ...Qué significa 'domesticar'?")
        self.dialogos.append(  "No eres de aquí Qué buscas?")
        self.dialogos.append(  "Busco a los hombres ")
        self.dialogos.append(  "Qué significa “domesticar”? ")
        self.dialogos.append(  "Los hombres  tienen fusiles y cazan. Es muy molesto. También crían gallinas. Es su único interés. Buscas gallinas?")
        self.dialogos.append(  "No. Busco amigos. Qué significa 'domesticar'? ")
        self.dialogos.append(  "Es una cosa demasiado olvidada. Significa 'crear lazos'.")
        self.dialogos.append(  "Crear lazos? ")
        self.dialogos.append(  "Sí .Para mí no eres todavía más que un muchachito semejante a cien mil muchachitos. Y no te necesito. Y tú tampoco me necesitas. No soy para ti más que un zorro semejante a cien mil zorros. Pero si me domesticas, tendremos necesidad el uno del otro. Serás para mí único en el mundo. Seré para ti único en el mundo...")
        self.dialogos.append(  "Empiezo a comprender. Hay una flor... Creo que me ha domesticado...  ")
        self.dialogos.append(  "Es posible. En la Tierra se ve toda clase de cosas...!  ")
        self.dialogos.append(  "Oh! No es en la Tierra ")
        self.dialogos.append(  "En otro planeta? ")
        self.dialogos.append(  "Sí ")
        self.dialogos.append(  "Hay cazadores en ese planeta? ")
        self.dialogos.append(  "No ")
        self.dialogos.append(  "Es interesante eso! Y gallinas? ")
        self.dialogos.append(  "No ")
        self.dialogos.append(  "No hay nada perfecto ")
        self.dialogos.append(  "Mi vida es monótona. Cazo gallinas, los hombres me cazan. Todas las gallinas se parecen y todos los hombres se parecen. Me aburro, pues, un poco. Pero, si me domesticas, mi vida se llenará de sol ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  " Conoceré un ruido de pasos que será diferente de todos los otros. Los otros pasos me hacen esconder bajo la tierra. El tuyo me llamará fuera de la madriguera, como una música. Y además, mira! Ves, allá, los campos de trigo? Yo no como pan. Para mí el trigo es inútil. Los campos de trigo no me recuerdan nada. Es bien triste! Pero tú tienes cabellos color de oro. Cuando me hayas domesticado, será maravilloso! El trigo dorado será un recuerdo de ti. Y amaré el ruido del viento en el trigo...Por favor... domestícame! ")
        self.dialogos.append(  "Bien lo quisiera, pero no tengo mucho tiempo. Tengo que encontrar amigos y conocer muchas cosas. ")
        self.dialogos.append(  "Sólo se conocen las cosas que se domestican.  Los hombres ya no tienen tiempo de conocer nada. Compran cosas hechas a los mercaderes. Pero como no existen mercaderes de amigos, los hombres ya no tienen amigos. Si quieres un amigo, domestícame! ")
        self.dialogos.append(  "Qué hay que hacer? ")
        self.dialogos.append(  "Hay que ser paciente Te sentarás al principio un poco lejos de mí, así, en la hierba. Te miraré de reojo y no dirás nada. La palabra es fuente de malentendidos. Pero, cada día, podrás sentarte un poco más cerca... ")
        #Narración Día siguiente jiji
        self.dialogos.append(  "Hubiese sido mejor venir a la misma hora. Si vienes, por ejemplo, a las cuatro de la tarde, comenzaré a ser feliz desde las tres. Cuanto más avance la hora, más feliz me sentiré. A las cuatro me sentiré agitado e inquieto; descubriré el precio de la felicidad! Pero si vienes a cualquier hora, nunca sabré a qué hora preparar mi corazón... Los ritos son necesarios. ")
        self.dialogos.append(  "Qué es un rito? ")
        self.dialogos.append(  "Es también algo demasiado olvidado. Es lo que hace que un día sea diferente de los otros días; una hora, de las otras horas. Entre los cazadores, por ejemplo, hay un rito. El jueves bailan con las muchachas del pueblo. El jueves es, pues, un día maravilloso. Voy a pasearme hasta la viña. Si los cazadores no bailaran en día fijo, todos los días se parecerían y yo no tendría vacaciones. ")
        #NARRACIÓN El principito domesticó al zorro
    def DiecisieteDespedidaZorro(self):
        self.dialogos.clear()
        self.dialogos.append(  "Ah!... Voy a llorar")
        self.dialogos.append(  "Tuya es la culpa. No deseaba hacerte mal, pero quisiste que te domesticara... ")
        self.dialogos.append(  "Sí  ")
        self.dialogos.append(  "Pero vas a llorar! ")
        self.dialogos.append(  "Sí ")
        self.dialogos.append(  "Entonces, no ganas nada. ")
        self.dialogos.append(  "Gano, por el color del trigo. Ve y mira nuevamente las rosas. Comprenderás que la tuya es única en el mundo. Volverás para decirme adiós y te regalaré un secreto. ")
        #Se vuelven a ver las rosas
        self.dialogos.append(  "No sois en absoluto parecidas a mi rosa; no sois nada aún.Nadie os ha domesticado y no habéis domesticado a nadie. Sois como era mi zorro. No era más que un zorro semejante a cien mil otros. Pero yo lo hice mi amigo y ahora es único en el mundo.")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Sois bellas, pero estáis vacías. No se puede morir por vosotras. Sin duda que un transeúnte común creerá que mi rosa se os parece. Pero ella sola es más importante que todas vosotras, puesto que es ella la rosa a quien regado, a quien puse bajo un globo, abrigué con el biombo, cuyas orugas maté (salvo las dos o tres que se hicieron mariposas). Puesto que es ella la rosa a la que escuché quejarse, o alabarse, o aun, algunas veces, callarse. Puesto que ella es mi rosa.")
        #Regresa con el zorro
        self.dialogos.append(  "Adiós  ")
        self.dialogos.append(  "Adiós. He aquí mi secreto. Es muy simple: no se ve bien sino con el corazón. Lo esencial es invisible a los ojos. ")
        self.dialogos.append(  "Lo esencial es invisible a los ojos ")
        self.dialogos.append(  "El tiempo que perdiste por tu rosa hace que tu rosa sea tan importante. ")
        self.dialogos.append(  "El tiempo que perdí por mi rosa... ")
        self.dialogos.append(  "Los hombres han olvidado esta verdad, pero tú no debes olvidarla. Eres responsable para siempre de lo que has domesticado. Eres responsable de tu rosa...  ")
        self.dialogos.append(  "Soy responsable de mi rosa...  ")
    def DieciochoPozo(self):
        self.dialogos.clear()
        self.dialogos.append(  "Ah! Tus recuerdos son bien lindos, pero todavía no he reparado mi avión, no tengo nada para beber y  sería feliz si pudiera caminar muy suavemente hacia una fuente. ")
        self.dialogos.append(  "Mi amigo el zorro... ")
        self.dialogos.append(  "Mi pequeño hombrecito, ya no se trata más del zorro! ")
        self.dialogos.append(  "Por qué? ")
        self.dialogos.append(  "Porque nos vamos a morir de sed... ")
        self.dialogos.append(  "Es bueno haber tenido un amigo, aun si vamos a morir. Yo estoy muy contento de haber tenido un amigo zorro... Tengo sed también... Busquemos un pozo...")
        #CAMINAN LA POZO
        self.dialogos.append(  "También tú tienes sed? ")
        self.dialogos.append(  "El agua puede también ser buena para el corazón... Las estrellas son bellas, por una flor que no se ve...")
        self.dialogos.append(  "Seguramente... ")
        self.dialogos.append(  "El desierto es bello ")
        self.dialogos.append(  "Sí ")
        self.dialogos.append(  "Lo que embellece al desierto  es que esconde un pozo en cualquier parte... ")
        self.dialogos.append(  "Sí,  ya se trate de la casa, de las estrellas o del desierto, lo que los embellece es invisible. ")
        self.dialogos.append(  "Me gusta que estés de acuerdo con mi zorro")
        #Camina el aviador cargando al principito hasta el alba
        self.dialogos.append(  "Los hombres se encierran en los rápidos pero no saben lo que buscan. Entonces se agitan y dan vueltas...No vale la pena...")
        self.dialogos.append(  "Este pozo es extraño. Todo está listo: la roldana, el balde y la cuerda...  ")
        self.dialogos.append(  "Oyes?  Hemos despertado al pozo y el pozo canta... ")
        self.dialogos.append(  "Déjame a mí. Es demasiado pesado para ti   ")
        self.dialogos.append(  "Tengo sed de esta agua.  Dame de beber...")
        #Los dos toman awita
        self.dialogos.append(  "En tu tierra los hombres cultivan cinco mil rosas en un mismo jardín... Y no encuentran lo que buscan... ")
        self.dialogos.append(  "No lo encuentran... ")
        self.dialogos.append(  "Y, sin embargo, lo que buscan podría encontrarse en una sola rosa o en un poco de agua... ")
        self.dialogos.append(  "Seguramente ")
        self.dialogos.append(  "Pero los ojos están ciegos. Es necesario buscar con el corazón...Es necesario que cumplas tu promesa ")
        self.dialogos.append(  "Qué promesa? ")
        self.dialogos.append(  "Tú lo sabes... un bozal para mi cordero... soy responsable de esa flor!  ")
        self.dialogos.append(  "Sacaré mi cuaderno de notas... ")
        self.dialogos.append(  "Tus baobabs se parecen un poco a los repollos... ")
        self.dialogos.append(  "Oh! Yo que estaba tan orgulloso de los baobabs!")
        self.dialogos.append(  "Tu zorro... las orejas... parecen cuernos... y son demasiado largas!  ")
        #C rie
        self.dialogos.append(  "Eres injusto, hombrecito; yo no sabía dibujar más que las boas cerradas y las boas abiertas.")
        self.dialogos.append(  "Oh, está bien! Los niños saben ")
        self.dialogos.append(  "Toma el bozal...Hombrecito...Tienes proyectos que ignoro...  ")
        self.dialogos.append(  " Sabes, mi caída sobre la Tierra... mañana será el aniversario... ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Caí muy cerca de aquí ")
        self.dialogos.append(  "Entonces, no te paseabas por casualidad la mañana que te conocí, hace ocho días, así, solo, a mil millas de todas las regiones habitadas. Volvías hacia el punto de tu caída? ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Tal vez, por el aniversario...? ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Ah! . Temo que... ")
        self.dialogos.append(  "Debes trabajar ahora. Debes volver a tu máquina. Te espero aquí. Vuelve mañana por la tarde... ")
    def DiecinueveByePrincipito(self):
        self.dialogos.clear()
        self.dialogos.append(  "No te acuerdas? No es exactamente aquí!  ")
        self.dialogos.append(  "*Inaudible* ")
        self.dialogos.append(  "Sí! Sí! Es el día, pero el lugar no es aquí... ")
        self.dialogos.append(  "*Inaudible* ")
        self.dialogos.append(  "... Seguro. Verás dónde comienza mi rastro en la arena. No tienes más que esperarme allí. Estaré allí esta noche. ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Tienes buen veneno? Estás segura de no hacerme sufrir mucho tiempo?...Ahora, vete... ")
        #Se ve la serpiente
        self.dialogos.append(  "Qué historia es ésta? Ahora hablas con las serpientes? ")
        self.dialogos.append(  "Estoy contento de que hayas encontrado lo que faltaba a tu máquina. Vas a poder volver a tu casa... ")
        self.dialogos.append(  "Cómo lo sabes? ")
        self.dialogos.append(  "Yo también, hoy vuelvo a mi casa... Es mucho más lejos... Es mucho más difícil...")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Tengo tu cordero. Y tengo la caja para el cordero. Y tengo el bozal... ")
        self.dialogos.append(  "Has tenido miedo, hombrecito. ")
        self.dialogos.append(  "Tendré mucho más miedo esta noche... ")
        self.dialogos.append(  "Hombrecito... quiero oírte reír otra vez... ")
        self.dialogos.append(  "Esta noche, hará un año. Mi estrella se encontrará exactamente sobre el lugar donde caí el año pasado... ")
        self.dialogos.append(  "Hombrecito, verdad que es un mal sueño esa historia de la serpiente, de la cita y de la estrella?... ")
        self.dialogos.append(  "No se ve lo que es importante... ")
        self.dialogos.append(  "Seguramente... ")
        self.dialogos.append(  "Es como con la flor. Si amas a una flor que se encuentra en una estrella, es agradable mirar el cielo por la noche. Todas las estrellas están florecidas. ")
        self.dialogos.append(  "Seguramente... ")
        self.dialogos.append(  "Por la noche mirarás las estrellas. No te puedo mostrar dónde se encuentra la mía, porque mi casa es muy pequeña. Será mejor así. Mi estrella será para ti una de las estrellas. Entonces te agradará mirar todas las estrellas... Todas serán tus amigas. Y luego te voy a hacer un regalo... ")
        #El principito C rie
        self.dialogos.append(  "Ah!, hombrecito... hombrecito... Me gusta oír tu risa! ")
        self.dialogos.append(  "Precisamente, será mi regalo... Será como con el agua... ")
        self.dialogos.append(  "Qué quieres decir? ")
        self.dialogos.append(  "Las gentes tienen estrellas que no son las mismas. Para unos, los que viajan, las estrellas son guías. Para otros, no son más que lucecitas. Para otros, que son sabios, son problemas. Para mi hombre de negocios, eran oro. Pero todas esas estrellas no hablan. Tú tendrás estrellas como nadie las ha tenido. ")
        self.dialogos.append(  "Qué quieres decir? ")
        self.dialogos.append(  "Cuando mires al cielo, por la noche, como yo habitaré en una de ellas, como yo reiré en una de ellas, será para ti como si rieran todas las estrellas. Tú tendrás estrellas que saben reír ")
        self.dialogos.append(  "Y cuando te hayas consolado (siempre se encuentra consuelo) estarás contento de haberme conocido. Serás siempre mi amigo. Tendrás deseos de reír conmigo. Y abrirás a veces tu ventana, así... por placer... Y tus amigos se asombrarán al verte reír mirando el cielo. Entonces les dirás: “Sí, las estrellas siempre me hacen reír”, y ellos te creerán loco. Te habré hecho una muy mala jugada... ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Será como si te hubiera dado en lugar de estrellas un montón de cascabelitos que saben reír...  ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Esta noche... sabes?... no llega. ")
        self.dialogos.append(  "No me separaré de ti. ")
        self.dialogos.append(  "Parecerá que sufro... Parecerá un poco que me muero. Es así. No vengas a verlo, no vale la pena... ")
        self.dialogos.append(  "No me separaré de ti.  ")
        self.dialogos.append(  "Te digo esto... también por la serpiente. No debe morderte... Las serpientes son malas. Pueden morder por placer... ")
        self.dialogos.append(  "No me separaré de ti. ")
        self.dialogos.append(  "Es cierto que no tienen veneno en la segunda mordedura... ")
        #Se hace de nochesita
    def Veinte(self):
        self.dialogos.clear()
        self.dialogos.append(  "Has hecho mal en estar aquí. Vas a sufrir. Parecerá que me he muerto y no será verdad... ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Comprendes. Es demasiado lejos. No puedo llevar mi cuerpo allí. Es demasiado pesado ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Pero será como una vieja corteza abandonada. No son tristes las viejas cortezas. ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Sabes?, será agradable. Yo también miraré las estrellas. Todas las estrellas serán pozos con una roldana enmohecida. Todas las estrellas me darán de beber... ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Será tan divertido! Tendrás quinientos millones de cascabeles y tendré quinientos millones de fuentes... ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Sabes?... mi flor... soy responsable. Y es tan débil! Y es tan ingenua! Tiene cuatro espinas insignificantes para protegerse contra el mundo... ")
        self.dialogos.append(  "... ")
        self.dialogos.append(  "Bien... Eso es todo... ")
        #Narración de cierre